### ISSUE TITLE
Improve performance: ClientHandler.OnPaint

### ISSUE THREAD

**Issue by allestuetsmerweh** [allestuetsmerweh/garden.cefpython#30]
rather than calling `buf.GetString`, which probably copies the whole buffer, call [`buf.GetIntPointer`](https://github.com/cztomczak/cefpython/blob/f5154031aea10e01f3a7fc016f93031f9725fff7/api/PaintBuffer.md#getintpointer).

Then create a Python [`MemoryView`](https://docs.python.org/3/c-api/memoryview.html) with `PyMemoryView_FromMemory`.

Finally, [blit](https://kivy.org/docs/api-kivy.graphics.texture.html?highlight=texture#blitting-custom-data) that `MemoryView` into the kivy texture of the widget.

**Comment by allestuetsmerweh** [comment]
See https://github.com/nickhutchinson/elevate/blob/master/elevate/pyapi.py on how to use

**Comment by allestuetsmerweh** [comment]
Solved for Py3. Wontfix for Py2.

**Comment by cztomczak** [comment]
Was there an issue with implementing this in Python 2?

**Comment by allestuetsmerweh** [comment]
You can see the Py2 code I wrote here: https://github.com/allestuetsmerweh/garden.cefpython/blob/cef50/cefbrowser/cefbrowser.py#L1175
I got a segfault when using the code, so I commented it out.
